# Section pour le build du site statique
[build]
  publish = "public"

# Section dédiée à la configuration des fonctions serverless
[functions]
  directory = "netlify/functions"

# Vos règles de redirection (cette partie est correcte)
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200