[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "public"
  environment = { PYTHON_VERSION = "3.13" }

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200